import type { PlanRequest, PlanResult, TaskSizeAssessment, WorkflowStep } from '../agent/types/contracts';

function inferEstimatedFiles(request: PlanRequest): number {
    if (typeof request.estimatedFiles === 'number') {
        return request.estimatedFiles;
    }

    const text = `${request.goal} ${(request.constraints ?? []).join(' ')}`.toLowerCase();
    const filePattern = /(\d+)\s*files?/;
    const match = filePattern.exec(text);
    if (match) {
        return Number.parseInt(match[1], 10);
    }

    return 1;
}

export function assessTaskSize(request: PlanRequest): TaskSizeAssessment {
    const reasons: string[] = [];
    const estimatedFiles = inferEstimatedFiles(request);
    const domainCount = request.domains?.length ?? 1;

    if (estimatedFiles >= 5) {
        reasons.push('estimated files >= 5');
    }

    if (domainCount >= 2) {
        reasons.push('multiple domains');
    }

    const complexityKeywords = ['refactor', 'rewrite', 'migrate', 'end-to-end', 'full system'];
    const hasComplexKeywords = complexityKeywords.some((word) =>
        request.goal.toLowerCase().includes(word)
    );
    if (hasComplexKeywords) {
        reasons.push('complexity keywords detected');
    }

    return {
        isLarge: reasons.length > 0,
        reasons,
        estimatedFiles,
        domainCount,
    };
}

export function decomposeIntoAtomicSteps(request: PlanRequest): WorkflowStep[] {
    const size = assessTaskSize(request);

    if (!size.isLarge) {
        return [
            {
                id: 'execute-scoped-task',
                title: 'Execute scoped task directly',
                status: 'pending',
                owner: 'executor',
                notes: ['Task considered small by decomposition policy.'],
            },
        ];
    }

    const chunkSize = Math.max(1, Math.min(4, Math.ceil(size.estimatedFiles / 3)));
    const chunkCount = Math.max(2, Math.ceil(size.estimatedFiles / chunkSize));

    const steps: WorkflowStep[] = [
        {
            id: 'analyze-requirements',
            title: 'Analyze requirements and constraints',
            status: 'pending',
            owner: 'planner',
            notes: size.reasons,
        },
    ];

    for (let index = 1; index <= chunkCount; index += 1) {
        steps.push({
            id: `execute-chunk-${index}`,
            title: `Execute chunk ${index}/${chunkCount} (≤${chunkSize} files)`,
            status: 'pending',
            owner: 'executor',
            notes: ['Atomic execution chunk generated by policy.'],
        });
    }

    steps.push({
        id: 'verify-and-close',
        title: 'Run verification and close workflow',
        status: 'pending',
        owner: 'executor',
        notes: ['Final verification gate.'],
    });

    return steps;
}

export function runMultiStepFlow(request: PlanRequest): PlanResult {
    const size = assessTaskSize(request);
    const steps: WorkflowStep[] = decomposeIntoAtomicSteps(request);

    return {
        projectId: request.projectId,
        summary: size.isLarge
            ? `Decomposed large workflow (${size.reasons.join(', ')})`
            : 'Generated scoped workflow plan.',
        steps,
    };
}
